//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentalfinalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public Nullable<int> PropertyManagerID { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
