//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentalfinalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalAgreement
    {
        public int AgreementID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public Nullable<int> ApartmentID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string PaymentStatus { get; set; }
        public decimal MonthlyRent { get; set; }
        public System.DateTime DueDate { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual User User { get; set; }
    }
}
